header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - "**/*.go"
    - "**/*.s"

  paths-ignore:
    - wire.go
    - examples/fastpb_gen/**
    - benchmark/fastpb_gen/**
    - benchmark/gogo_gen/**

  comment: on-failure
