// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: pet/pet.proto

package pet

import (
	user "github.com/cloudwego/fastpb/examples/fastpb_gen/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age   int32      `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Owner string     `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Group user.Group `protobuf:"varint,4,opt,name=group,proto3,enum=user.Group" json:"group,omitempty"`
}

func (x *Pet) Reset() {
	*x = Pet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pet_pet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_pet_pet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_pet_pet_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Pet) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Pet) GetGroup() user.Group {
	if x != nil {
		return x.Group
	}
	return user.Group(0)
}

var File_pet_pet_proto protoreflect.FileDescriptor

var file_pet_pet_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x65, 0x74, 0x2f, 0x70, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x70, 0x65, 0x74, 0x1a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x03, 0x50, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77,
	0x65, 0x67, 0x6f, 0x2f, 0x66, 0x61, 0x73, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2f, 0x66, 0x61, 0x73, 0x74, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70,
	0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pet_pet_proto_rawDescOnce sync.Once
	file_pet_pet_proto_rawDescData = file_pet_pet_proto_rawDesc
)

func file_pet_pet_proto_rawDescGZIP() []byte {
	file_pet_pet_proto_rawDescOnce.Do(func() {
		file_pet_pet_proto_rawDescData = protoimpl.X.CompressGZIP(file_pet_pet_proto_rawDescData)
	})
	return file_pet_pet_proto_rawDescData
}

var file_pet_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pet_pet_proto_goTypes = []interface{}{
	(*Pet)(nil),     // 0: pet.Pet
	(user.Group)(0), // 1: user.Group
}
var file_pet_pet_proto_depIdxs = []int32{
	1, // 0: pet.Pet.group:type_name -> user.Group
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pet_pet_proto_init() }
func file_pet_pet_proto_init() {
	if File_pet_pet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pet_pet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pet_pet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pet_pet_proto_goTypes,
		DependencyIndexes: file_pet_pet_proto_depIdxs,
		MessageInfos:      file_pet_pet_proto_msgTypes,
	}.Build()
	File_pet_pet_proto = out.File
	file_pet_pet_proto_rawDesc = nil
	file_pet_pet_proto_goTypes = nil
	file_pet_pet_proto_depIdxs = nil
}
