// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: user/player/player.proto

package playercustom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerKind int32

const (
	PlayerKind_STRENGTH     PlayerKind = 0
	PlayerKind_AGILITY      PlayerKind = 1
	PlayerKind_INTELLECTUAL PlayerKind = 2
)

// Enum value maps for PlayerKind.
var (
	PlayerKind_name = map[int32]string{
		0: "STRENGTH",
		1: "AGILITY",
		2: "INTELLECTUAL",
	}
	PlayerKind_value = map[string]int32{
		"STRENGTH":     0,
		"AGILITY":      1,
		"INTELLECTUAL": 2,
	}
)

func (x PlayerKind) Enum() *PlayerKind {
	p := new(PlayerKind)
	*p = x
	return p
}

func (x PlayerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_user_player_player_proto_enumTypes[0].Descriptor()
}

func (PlayerKind) Type() protoreflect.EnumType {
	return &file_user_player_player_proto_enumTypes[0]
}

func (x PlayerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerKind.Descriptor instead.
func (PlayerKind) EnumDescriptor() ([]byte, []int) {
	return file_user_player_player_proto_rawDescGZIP(), []int{0}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind  PlayerKind `protobuf:"varint,3,opt,name=kind,proto3,enum=player.PlayerKind" json:"kind,omitempty"`
	Level int32      `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp   int32      `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_player_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_user_player_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_user_player_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetKind() PlayerKind {
	if x != nil {
		return x.Kind
	}
	return PlayerKind_STRENGTH
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_user_player_player_proto protoreflect.FileDescriptor

var file_user_player_player_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x22, 0x7c, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70,
	0x2a, 0x39, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0c,
	0x0a, 0x08, 0x53, 0x54, 0x52, 0x45, 0x4e, 0x47, 0x54, 0x48, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x41, 0x47, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x54,
	0x45, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x55, 0x41, 0x4c, 0x10, 0x02, 0x42, 0x4a, 0x5a, 0x48, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x77,
	0x65, 0x67, 0x6f, 0x2f, 0x66, 0x61, 0x73, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2f, 0x66, 0x61, 0x73, 0x74, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x3b, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_player_player_proto_rawDescOnce sync.Once
	file_user_player_player_proto_rawDescData = file_user_player_player_proto_rawDesc
)

func file_user_player_player_proto_rawDescGZIP() []byte {
	file_user_player_player_proto_rawDescOnce.Do(func() {
		file_user_player_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_player_player_proto_rawDescData)
	})
	return file_user_player_player_proto_rawDescData
}

var file_user_player_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_player_player_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_player_player_proto_goTypes = []interface{}{
	(PlayerKind)(0), // 0: player.PlayerKind
	(*Player)(nil),  // 1: player.Player
}
var file_user_player_player_proto_depIdxs = []int32{
	0, // 0: player.Player.kind:type_name -> player.PlayerKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_player_player_proto_init() }
func file_user_player_player_proto_init() {
	if File_user_player_player_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_player_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_player_player_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_player_player_proto_goTypes,
		DependencyIndexes: file_user_player_player_proto_depIdxs,
		EnumInfos:         file_user_player_player_proto_enumTypes,
		MessageInfos:      file_user_player_player_proto_msgTypes,
	}.Build()
	File_user_player_player_proto = out.File
	file_user_player_player_proto_rawDesc = nil
	file_user_player_player_proto_goTypes = nil
	file_user_player_player_proto_depIdxs = nil
}
