// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package playercustom

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *Player) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Player[number], err)
}

func (x *Player) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *Player) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Name, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Player) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Kind = PlayerKind(v)
	return offset, nil
}

func (x *Player) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Level, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *Player) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.Exp, offset, err = fastpb.ReadInt32(buf, _type)
	return offset, err
}

func (x *Player) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *Player) fastWriteField1(buf []byte) (offset int) {
	if x.Id == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, x.GetId())
	return offset
}

func (x *Player) fastWriteField2(buf []byte) (offset int) {
	if x.Name == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetName())
	return offset
}

func (x *Player) fastWriteField3(buf []byte) (offset int) {
	if x.Kind == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, int32(x.GetKind()))
	return offset
}

func (x *Player) fastWriteField4(buf []byte) (offset int) {
	if x.Level == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 4, x.GetLevel())
	return offset
}

func (x *Player) fastWriteField5(buf []byte) (offset int) {
	if x.Exp == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 5, x.GetExp())
	return offset
}

func (x *Player) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *Player) sizeField1() (n int) {
	if x.Id == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, x.GetId())
	return n
}

func (x *Player) sizeField2() (n int) {
	if x.Name == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetName())
	return n
}

func (x *Player) sizeField3() (n int) {
	if x.Kind == 0 {
		return n
	}
	n += fastpb.SizeInt32(3, int32(x.GetKind()))
	return n
}

func (x *Player) sizeField4() (n int) {
	if x.Level == 0 {
		return n
	}
	n += fastpb.SizeInt32(4, x.GetLevel())
	return n
}

func (x *Player) sizeField5() (n int) {
	if x.Exp == 0 {
		return n
	}
	n += fastpb.SizeInt32(5, x.GetExp())
	return n
}

var fieldIDToName_Player = map[int32]string{
	1: "Id",
	2: "Name",
	3: "Kind",
	4: "Level",
	5: "Exp",
}
